# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce3e4600bd1412bc365c64464f6fcc4610c6814bf4d8cd509f039e6b4a4ea517266b42815ab5e6e9a3f08ebd2443e51d9502617121a01df64fdc4a179279e339

test:
  secret_key_base: 6575dbe511c6bed466b43747da3268471af77fe7c7b0796372e80df9073813e89ef9bf8dace8ad4b9ba1a64eb076df9abeb050879c6b1b63369c887caacf6dfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
